### ISSUE TITLE
Portal feature

### ISSUE THREAD

**Issue by mani1232** [Folia-Inquisitors/MoreFoWorld#8]
Add setting to disable it...

**Comment by mani1232** [comment]
For enable vanilla

**Comment by HSGamer** [comment]
Deal with it. 
If you link worlds via portals using this plugin, you have to deal with the behavior. The vanilla behavior doesn't exist here and Folia doesn't support that unless you use the default worlds.
So, don't use the link portal feature and only use default worlds if you want "vanilla behavior" with that. Or, go and ask Folia to add support for proper portal events.

**Comment by mani1232** [comment]
@HSGamer Before its works fine, im need disable this, im dont use it, im use world -> portal -> nether (vanilla)
And for custom worlds /warp command...
Im not need portal feature, and im want disable it

**Comment by HSGamer** [comment]
> @HSGamer Before its works fine, im need disable this, im dont use it, im use world -> portal -> nether (vanilla)
> And for custom worlds /warp command...
> Im not need portal feature, and im want disable it

Check your portal config to see if you accidentally set it.
Remove it if you did.

**Comment by mani1232** [comment]
> > @HSGamer Before its works fine, im need disable this, im dont use it, im use world -> portal -> nether (vanilla)
> > And for custom worlds /warp command...
> > Im not need portal feature, and im want disable it
> 
> Check your portal config to see if you accidentally set it. Remove it if you did.

if it removed ALL portals dont working, include vanilla
